version: '2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.release
    env_file: ./.env
    image: tsdp/backend
    volumes:
      - ./backend/src:/srv/app
      - api-static:/srv/app/static/
    links:
      - db:db
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/tsdp.conf:/etc/nginx/conf.d/default.conf
      - api-static:/srv/static:ro
    links:
      - backend:backend

volumes:
  pgdata:
  api-static:
