version: '2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:3-alpine

  backend:
    build: ./backend
    image: tsdp/backend
    env_file: ./.env
    # tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/srv/app
    links:
      - db:db
    depends_on:
      - db

  celery:
    image: tsdp/backend
    env_file: ./.env
    environment:
      - DEBUG=off
    command: celery -A tsdp worker -l info
    volumes:
      - ./backend/src:/srv/app
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis

volumes:
  pgdata:
