version: '2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  backend:
    build: ./backend
    env_file: ./.env
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/srv/app
    links:
      - db:db
    depends_on:
      - db

volumes:
  pgdata:
