# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='name')),
                ('name_plural', models.CharField(blank=True, max_length=63, null=True, verbose_name='name plural')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='name')),
                ('symbol', models.CharField(max_length=32, unique=True, verbose_name='symbol')),
                ('decimal_places', models.IntegerField(default=5, verbose_name='decimal places')),
                ('subscribed', models.BooleanField(db_index=True, default=True, verbose_name='subscribed')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Group')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuoteDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('open', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='open')),
                ('high', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='high')),
                ('low', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='low')),
                ('close', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='close')),
                ('volume', models.BigIntegerField(default=0, verbose_name='volume')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Instrument')),
            ],
            options={
                'verbose_name': 'Quote daily',
                'verbose_name_plural': 'Quotes daily',
            },
        ),
        migrations.AlterUniqueTogether(
            name='quotedaily',
            unique_together=set([('instrument', 'date')]),
        ),
    ]
